### PR TITLE
fix: open directory on edit

### PR DESCRIPTION
**Pull request by bennyyip**

### CODE REVIEW

**Comment by habamax** [comment]
What it fixes?

**Comment by bennyyip** [comment]
It failed to open directory yesterday. But I cannot reproduce it now.
Sorry for wasting your time.

**Comment by habamax** [comment]
No worries, if you happen to figure out how to reproduce it, pls let me know.

**Comment by bennyyip** [comment]
It should be my problem. I tried it on an empty config vim, it works.

**Pull request closed without merging**
